import type { Metadata } from "next";
import { Inter, Source_Serif_4, STIX_Two_Text } from "next/font/google";
import "./globals.css";
import MainHeader from "@/components/header/Header";
import localFont from "next/font/local";
import Footer from "@/components/footer/footer";

const inter = Inter({ subsets: ["latin"] });
const sourceSerif = Source_Serif_4({
  subsets: ["latin"],
  variable: "--font-source-serif-4",
});
const stixToText = STIX_Two_Text({
  subsets: ["latin"],
  variable: "--font-stix-to-text",
});

const renner = localFont({
  src: "./renner.ttf",
  variable: "--font-renner",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${sourceSerif.variable} ${stixToText.variable} ${renner.variable}`}
      >
        <main className="relative w-full bg-white">
          <MainHeader />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
