import type { Metadata } from "next";
import {
  Inter,
  Source_Serif_4,
  STIX_Two_Text,
  Playball,
  Alex_Brush,
  Raleway,
} from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });
const sourceSerif = Source_Serif_4({
  subsets: ["latin"],
  variable: "--font-source-serif-4",
});
const stixToText = STIX_Two_Text({
  subsets: ["latin"],
  variable: "--font-stix-to-text",
});

const raleWay = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
});

const renner = localFont({
  src: "./renner.ttf",
  variable: "--font-renner",
});

const playball = Playball({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-pb",
});

const alexBrush = Alex_Brush({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-ab",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${raleWay.variable} ${playball.variable} ${alexBrush.variable} ${sourceSerif.variable} ${stixToText.variable} ${renner.variable}`}
      >
        <main className="relative w-full bg-white">{children}</main>
      </body>
    </html>
  );
}
